#!/usr/bin/env python
"""isort:skip_file
"""
import os
import sys; sys.path.append(os.path.join(os.path.abspath(os.path.dirname(__file__)), ".."))  # noqa

from molten.contrib.sqlalchemy import Session

from {{cookiecutter.package_name}}.app import setup_app

_, app = setup_app()


def populate_db(session: Session):
    session.commit()


app.injector.get_resolver().resolve(populate_db)()
